# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1.4
FROM node:lts-alpine AS builder

WORKDIR /app

# Install dependencies without running prepare scripts
COPY package.json package-lock.json tsconfig.json ./
RUN npm ci --ignore-scripts

# Copy source
COPY src ./src

# Build
RUN npm run build

# Runtime image
FROM node:lts-alpine AS runtime
WORKDIR /app
COPY --from=builder /app/build ./build
# Copy production dependencies only
COPY package.json package-lock.json ./
RUN npm ci --only=production --ignore-scripts

# Default command will be provided by MCP infrastructure via smithery
ENTRYPOINT ["node", "build/index.js"]
